theme = "onedark"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
"C-space" = "expand_selection"
"C-/" = "toggle_comments"

"A-down" = ["extend_to_line_bounds", "delete_selection", "paste_after"]
"A-up" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

[editor.indent-guides]
render = true
skip-levels = 0
